name: InvisibleInGrass
version: 1.0
main: com.Mooling0602.InvisibleInGrass.InvisiblePlugin
api-version: "1.20"
folia-supported: true
description: Makes players invisible in tall grass when sneaking.
author: Mooling0602